// KIOSK_DEFAULTS_V1: what every kiosk leaf seeded to on 2026-10-09, frozen. A share link stores
// only its differences from these, so they must never change, whatever the registry, the leaf
// defaults, DEFAULT_BASE, SEED_FIT, the kiosk labels or the instructions do later.
// Generated once; NEVER edit or regenerate an entry (old links would decode to other settings).
// A new kiosk leaf APPENDS its entry; oefenen.session.defaults.test.ts prints it and guards drift.

type Constraints = Record<string, unknown>;
// [typeId, kiosk label, default instruction, 1 = the leaf's instruction is a function of its
//  settings (resolved here at the seed), settings that differ from the type base, base keys absent]
type LeafRow = readonly [string, string, string, 0 | 1, Constraints?, (readonly string[])?];

// typeId → the seed of its first leaf in KIOSK_LEAF_TABLE_V1; the leaf rows diff against it.
const TYPES: Readonly<Record<string, Constraints>> = {
    vergelijken: { subType: 'getallen', maxGetal: 1000, numberMask: {}, chooseTarget: 'grootste', setSize: 3, decimalPlaces: 0, leftRep: 'breuk', rightRep: 'kommagetal', leftMask: {}, rightMask: {}, leftFracN: 4, leftFracD: 8, rightFracN: 4, rightFracD: 8 },
    afronden: { subType: 'simpel', numberType: 'natural', maxGetal: 1000, numberMask: {}, roundTargets: ['T', 'H'], roosterSize: 6, decimalPlaces: 2 },
    procenten: { subType: 'nemen', percents: [10, 25, 50], maxGetal: 1000, scaffold: false },
    'hr-std-optellen': { numberType: 'natural', decimalPlaces: 2, maxGetal: 1000, bridges: { E: 'FREE', T: 'FREE' }, operand1Mask: {}, operand2Mask: {}, fractionDifficulty: 'same', mixedNumber1: false, mixedNumber2: false, maxNumerator1: 10, maxDenominator1: 10, maxNumerator2: 10, maxDenominator2: 10, linkFractions: true },
    'hr-std-aftrekken': { numberType: 'natural', decimalPlaces: 2, maxGetal: 1000, bridges: { E: 'FREE', T: 'FREE' }, operand1Mask: {}, operand2Mask: {}, fractionDifficulty: 'same', mixedNumber1: false, mixedNumber2: false, maxNumerator1: 10, maxDenominator1: 10, maxNumerator2: 10, maxDenominator2: 10, linkFractions: true },
    'hr-std-vermenigvuldigen': { numberType: 'natural', decimalPlaces: 2, maxGetal: 1000, bridges: { E: 'FREE', T: 'FREE' }, operand1Mask: {}, operand2Mask: {}, fractionDifficulty: 'same', mixedNumber1: false, mixedNumber2: false, maxNumerator1: 10, maxDenominator1: 10, maxNumerator2: 10, maxDenominator2: 10, linkFractions: true, multiplicationMode: 'tafels', selectedTables: [2, 3, 4, 5, 10], tableLimit: 10 },
    'hr-std-delen': { numberType: 'natural', decimalPlaces: 2, maxGetal: 1000, bridges: { E: 'FREE', T: 'FREE' }, operand1Mask: {}, operand2Mask: {}, fractionDifficulty: 'same', mixedNumber1: false, mixedNumber2: false, maxNumerator1: 10, maxDenominator1: 10, maxNumerator2: 10, maxDenominator2: 10, linkFractions: true, multiplicationMode: 'tafels', selectedTables: [2, 3, 4, 5, 10], tableLimit: 10 },
    'hr-std-gemengd': { numberType: 'natural', decimalPlaces: 2, maxGetal: 1000, bridges: { E: 'FREE', T: 'FREE' }, operand1Mask: {}, operand2Mask: {}, fractionDifficulty: 'same', mixedNumber1: false, mixedNumber2: false, maxNumerator1: 10, maxDenominator1: 10, maxNumerator2: 10, maxDenominator2: 10, linkFractions: true, variants: ['+', '-', 'x', ':'], mix: 'random' },
    'cijferen-optellen-nat': { operator: '+', numberType: 'natural', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-optellen-dec': { operator: '+', numberType: 'decimal', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-aftrekken-nat': { operator: '-', numberType: 'natural', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-aftrekken-dec': { operator: '-', numberType: 'decimal', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-vermenigvuldigen-nat': { operator: 'x', numberType: 'natural', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-vermenigvuldigen-dec': { operator: 'x', numberType: 'decimal', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-delen-nat': { operator: ':', numberType: 'natural', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    'cijferen-delen-dec': { operator: ':', numberType: 'decimal', maxRange: 1000, decimalPlaces: 2, withEstimation: false, scaffolding: 3, withRemainder: false, numberOfTerms: 2, gridCellSize: 25, operand0Mask: {}, operand1Mask: {}, operand2Mask: {}, operand3Mask: {}, bridges: {}, extraCols: 0, extraRows: 0 },
    plaatswaarde: { subType: 'waarde', maxGetal: 1000, numberMask: {}, decimalPlaces: 0 },
    'even-oneven': { subType: 'cirkels', maxGetal: 100, target: 'even', perRow: 10 },
    'romeinse-cijfers': { subType: 'herkennen', niveau: 2 },
    getalfunctie: { functies: ['hoeveelheid', 'rang', 'maat', 'code'], answerMode: 'aankruisen', maxGetal: 1000 },
    'mab-herkennen': { mabStyle: 'symbolic', maxNumber: 1000, operand1Mask: {}, scaffolding: 'positietabel', exercisesPerRow: 3, boxHeight: 70, answerHeight: 36 },
    schattend: { operators: ['+', '-'], numberType: 'natural', maxGetal: 1000, decimalPlaces: 2, roundTargets: ['H'], scaffolding: 'tussenstappen', answerLine: 'kort' },
    rekenvolgorde: { operators: ['+', '-', 'x'], haakjesMode: 'MAG', opsCount: 2, maxGetal: 1000, tableLimit: 10 },
    controleren: { subType: 'negenproef', operators: ['+', '-'], maxGetal: 1000, foutAandeel: 'helft', showKruis: true },
    'vormleer-hoeken': { kind: 'hoek', mode: 'herkennen', answerMode: 'woordbank', classify: 'vierhoeken', concepts: ['scherp', 'recht', 'stomp'], randomRotation: true, showBoog: true, showEqualSides: true, showRightAngles: true, showParallel: false, rightAngleStyle: 'vierkantje', raster: true, boxHeight: 4, exercisesPerRow: 3, allowHorizontaal: false, allowVerticaal: false, nameAngles: true },
    'vormleer-figuren': { kind: 'figuur', mode: 'herkennen', answerMode: 'woordbank', classify: 'vierhoeken', concepts: ['vierkant', 'rechthoek', 'ruit', 'parallellogram', 'trapezium'], randomRotation: false, showBoog: true, showEqualSides: true, showRightAngles: true, showParallel: false, rightAngleStyle: 'vierkantje', raster: true, boxHeight: 4, exercisesPerRow: 3, allowHorizontaal: false, allowVerticaal: false, nameAngles: true },
    temperatuur: { variant: 'aflezen', includeNegatives: false, perRow: 4 },
    weegschaal: { mode: 'aflezen', bereikGram: 1000, stepGram: 50, notatie: 'g', exercisesPerRow: 2, boxHeight: 170 },
    oppervlakte: { subType: 'rooster', shapes: ['rechthoek', 'l-figuur'], minLength: 2, maxLength: 8, askOmtrek: false, scaffoldFormule: true },
    maateenheid: { grootheden: ['lengte', 'massa', 'inhoud'], answerMode: 'omcirkelen', subType: 'eenheid' },
    herleidingen: { measure: 'lengte', units: ['m', 'dm', 'cm', 'mm'], maxEnkel: 100, maxSamengesteld: 1000, formats: ['enkel-getal', 'enkel-eenheid', 'samengesteld-enkel', 'enkel-samengesteld'], compoundMode: '2', areMode: 'samengesteld', writeUnits: false, scaffolding: 'geen', herleidingLayout: 'uitlijnen', tablePrompt: false, tableAnswer: 'blank', tableCellW: 60, tableCellH: 30 },
    'geld-herkennen': { maxGetal: 1000, format: 'euros', scaffolding: 'invullen', geldLayout: 'samen', showVoorbeelden: false, voorbeeldTypes: [], exercisesPerRow: null, allowedDenominations: [50000, 20000, 10000, 5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5], boxHeight: 80 },
    'geld-teruggeven': { minPriceEuros: 1, maxPriceEuros: 49, payWithOptions: [1000, 2000, 5000], centenDeel: 'vijf', scaffolding: 'ingevuld', antwoordType: 'schrijven', antwoordFormat: 'euro-cent', betalenMetTekening: false, boxHeight: 120 },
    'geld-rekenen': { subType: 'korting', percents: [10, 25, 50], maxEuro: 100, wholeEuros: true, halfYear: false },
    'lengte-meten': { measureModel: 'meten', precision: 'cm', minLength: 3, maxLength: 10, maxCorners: 0, perSideScaffold: false, answerMode: 'single', answerUnit: 'cm', shapes: ['driehoek', 'rechthoek', 'vierkant'] },
    omtrek: { measureModel: 'meten', precision: 'cm', minLength: 3, maxLength: 10, maxCorners: 0, perSideScaffold: false, answerMode: 'single', answerUnit: 'cm', shapes: ['driehoek', 'rechthoek', 'vierkant'] },
    splitsen: { maxGetal: 10, operand1Mask: {}, operand2Mask: {}, fixedTotal: null, layout: 'basic', rowsPerBox: 4, rowHeight: 28 },
    ordenen: { numberType: 'natural', count: 3, operatorMode: 'oplopend', maxGetal: 1000, decimalPlaces: 2, unitFractionsOnly: false, allowMixed: false, answerStyle: 'lijn' },
    getallenas: { numberType: 'natural', maxGetal: 1000, step: 5, direction: 'right', hardMode: false, ticks: 6 },
    getallenrijen: { numberType: 'natural', maxGetal: 1000, step: 5, direction: 'right', hardMode: false, ticks: 6, numberMask: {}, fractionStep: 4, maxTeller: 25, showFrame: true },
    'breuken-rangschikken': { fractionMode: 'stambreuken', count: 4, operatorMode: 'oplopend', minDenominator: 2, maxDenominator: 10, answerStyle: 'lijn' },
    getalpatronen: { numberType: 'natural', maxGetal: 1000, ticks: 6, steps: 1, ops: ['+'], opSettings: { '+': { max: 10, mask: {} } }, maxDecimals: 1, showArrows: false, showOperators: false, operatorsShown: 0, operatorStyle: 'symbol' },
    kettingsommen: { numberType: 'natural', maxGetal: 1000, chainLength: 4, ops: ['+', '-'], opSettings: { '+': { max: 10 }, '-': { max: 10 } }, blankMiddle: false, showArrows: true, showOperators: true, operatorsShown: 99, operatorStyle: 'full' },
    deelbaarheid: { layout: 'veelvouden', divisors: [2, 5, 10], maxGetal: 1000, base: 9, terms: 6, givenCount: 2 },
    breuken: { subType: 'herkennen', shape: 'rectangle', shapes: ['rectangle'], minDenominator: 2, maxDenominator: 8, answerFormat: 'fraction-questions', objectShape: 'circle', maxTotal: 20, minLineLength: 4, maxLineLength: 12, level: 1, answerMode: 'berekeningslijnen', maxAbstractN3: 1000, staticSize: false, staticW: 4, staticH: 3, staticSide: 4, staticDiam: 4, groupingMode: 'standaard', drawBoxH: 3, showGrid: true },
    'breuken-bewerken': { subType: 'gemengd', direction: 'naar-gemengd', minDenominator: 2, maxDenominator: 10, maxNumerator: 10, tablesOnly: true, allowIrreducible: false, targetDen: '' },
    verbanden: { subType: 'tabel', reps: ['breuk', 'decimaal', 'procent'], denominators: [2, 4, 5, 10, 100], given: 'random' },
    'klok-kloklezen': { clockType: 'analoog', exerciseMode: 'lezen', is24hour: false, timeTypes: ['uren', 'halve_uren', 'kwartier_over', 'kwartier_voor'], minuteDirection: 'beide', handChoice: 'beide' },
    tijdsduur: { granularity: ['kwartier'], blanks: ['duur'], maxDuurMin: 240, overMidnight: false },
    'deelbaarheid-kleuren': { viewMode: 'strip', divisors: [2, 5, 10], maxGetal: 1000, perRow: 10, rasterCount: 100, rasterCols: 10, showRest: false },
    'geld-tekenen': { maxGetal: 1000, format: 'euros', scaffolding: 'eenvoudig', geldLayout: 'samen', showVoorbeelden: false, voorbeeldTypes: [], exercisesPerRow: null, allowedDenominations: [50000, 20000, 10000, 5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5], boxHeight: 80 },
    'geld-wissel': { exerciseBills: [500, 1000], exercisesPerRow: 2, boxHeight: 100 },
    'mab-tekenen': { mabStyle: 'symbolic', maxNumber: 1000, operand1Mask: {}, scaffolding: 'positietabel', exercisesPerRow: 3, boxHeight: 70, answerHeight: 36 },
};

const LEAVES: Readonly<Record<string, LeafRow>> = {
    'vergelijken-getallen': ['vergelijken', 'Vergelijken · twee getallen', 'Vul in: <, > of =.', 0],
    'afronden-nat-simpel': ['afronden', 'Afronden · natuurlijk · eenvoudig', 'Rond af op T en H.', 1],
    'afronden-dec-simpel': ['afronden', 'Afronden · decimaal · eenvoudig', 'Rond af op E en t.', 1, { numberType: 'decimal', maxGetal: 100, roundTargets: ['E', 't'] }],
    'procenten-nemen': ['procenten', 'Percent van een getal', 'Reken uit.', 0],
    'procenten-welk': ['procenten', 'Hoeveel procent?', 'Hoeveel procent is het?', 0, { subType: 'welk-percent' }],
    'hr-std-optellen-nat': ['hr-std-optellen', 'Optellen · natuurlijk', 'Reken uit.', 0],
    'hr-std-optellen-dec': ['hr-std-optellen', 'Optellen · decimaal', 'Reken uit.', 0, { numberType: 'decimal' }],
    'hr-std-aftrekken-nat': ['hr-std-aftrekken', 'Aftrekken · natuurlijk', 'Reken uit.', 0],
    'hr-std-aftrekken-dec': ['hr-std-aftrekken', 'Aftrekken · decimaal', 'Reken uit.', 0, { numberType: 'decimal' }],
    'hr-std-vermenigvuldigen-nat': ['hr-std-vermenigvuldigen', 'Vermenigvuldigen · natuurlijk', 'Reken uit.', 0],
    'hr-std-vermenigvuldigen-dec': ['hr-std-vermenigvuldigen', 'Vermenigvuldigen · decimaal', 'Reken uit.', 0, { numberType: 'decimal' }],
    'hr-std-delen-nat': ['hr-std-delen', 'Delen · natuurlijk', 'Reken uit.', 0],
    'hr-std-delen-dec': ['hr-std-delen', 'Delen · decimaal', 'Reken uit.', 0, { numberType: 'decimal' }],
    'hr-std-optellen-rat': ['hr-std-optellen', 'Optellen · breuken', 'Reken uit.', 0, { numberType: 'rational' }],
    'hr-std-aftrekken-rat': ['hr-std-aftrekken', 'Aftrekken · breuken', 'Reken uit.', 0, { numberType: 'rational' }],
    'hr-std-vermenigvuldigen-rat': ['hr-std-vermenigvuldigen', 'Vermenigvuldigen · breuken', 'Reken uit.', 0, { numberType: 'rational' }],
    'hr-std-delen-rat': ['hr-std-delen', 'Delen · breuken', 'Reken uit.', 0, { numberType: 'rational' }],
    'hr-std-gemengd-nat': ['hr-std-gemengd', 'Gemengd · natuurlijk', 'Reken uit.', 0],
    'hr-std-gemengd-dec': ['hr-std-gemengd', 'Gemengd · decimaal', 'Reken uit.', 0, { numberType: 'decimal' }],
    'cijferen-optellen-nat': ['cijferen-optellen-nat', 'Cijferen optellen · natuurlijk', 'Cijfer uit.', 0],
    'cijferen-optellen-dec': ['cijferen-optellen-dec', 'Cijferen optellen · decimaal', 'Cijfer uit.', 0],
    'cijferen-aftrekken-nat': ['cijferen-aftrekken-nat', 'Cijferen aftrekken · natuurlijk', 'Cijfer uit.', 0],
    'cijferen-aftrekken-dec': ['cijferen-aftrekken-dec', 'Cijferen aftrekken · decimaal', 'Cijfer uit.', 0],
    'cijferen-vermenigvuldigen-nat': ['cijferen-vermenigvuldigen-nat', 'Cijferen vermenigvuldigen · natuurlijk', 'Cijfer uit.', 0],
    'cijferen-vermenigvuldigen-dec': ['cijferen-vermenigvuldigen-dec', 'Cijferen vermenigvuldigen · decimaal', 'Cijfer uit.', 0],
    'cijferen-delen-nat': ['cijferen-delen-nat', 'Cijferen delen · natuurlijk', 'Cijfer uit.', 0],
    'cijferen-delen-dec': ['cijferen-delen-dec', 'Cijferen delen · decimaal', 'Cijfer uit.', 0],
    'plaatswaarde-waarde': ['plaatswaarde', 'Plaatswaarde benoemen · waarde van cijfer', 'Wat is de waarde van het onderstreepte cijfer?', 0],
    'plaatswaarde-plaats': ['plaatswaarde', 'Plaatswaarde benoemen · plaats benoemen', 'Op welke plaats staat het onderstreepte cijfer?', 0, { subType: 'plaats' }],
    'plaatswaarde-omcirkelen': ['plaatswaarde', 'Plaatswaarde benoemen · plaats omcirkelen', 'Omcirkel de plaats van het onderstreepte cijfer.', 0, { subType: 'omcirkelen' }],
    'vergelijken-kiezen': ['vergelijken', 'Vergelijken · grootste / kleinste', 'Omcirkel het grootste getal.', 1, { subType: 'kiezen' }],
    'vergelijken-representaties': ['vergelijken', 'Vergelijken · breuken & kommagetallen', 'Vul in: <, > of =.', 0, { subType: 'representaties', maxGetal: 10, decimalPlaces: 1 }],
    'even-oneven-cirkels': ['even-oneven', 'Even of oneven', 'Maak groepjes van twee. Even of oneven?', 0],
    'romeinse-herkennen': ['romeinse-cijfers', 'Romeinse cijfers lezen', 'Welk getal is dit?', 0],
    'romeinse-schrijven': ['romeinse-cijfers', 'Romeinse cijfers schrijven', 'Schrijf in Romeinse cijfers.', 0, { subType: 'schrijven' }],
    'getalbegrip-functie': ['getalfunctie', 'Functie van getallen', 'Wat betekent het getal? Kruis aan.', 1],
    'mab-herkennen': ['mab-herkennen', 'MAB · getallen herkennen', 'Welk getal is dit?', 0],
    'schattend-nat': ['schattend', 'Schattend rekenen · natuurlijk', 'Rond af en schat.', 1],
    'schattend-dec': ['schattend', 'Schattend rekenen · decimaal', 'Rond af en schat.', 1, { numberType: 'decimal', maxGetal: 100, roundTargets: ['E'] }],
    'handig-rekenvolgorde': ['rekenvolgorde', 'Rekenvolgorde en haakjes', 'Reken uit. Let op de volgorde van de bewerkingen.', 0],
    'controleren-negenproef': ['controleren', 'Negenproef', 'Controleer met de negenproef.', 0],
    'controleren-omgekeerde': ['controleren', 'Omgekeerde bewerking', 'Reken uit en controleer met de omgekeerde bewerking.', 0, { subType: 'omgekeerde' }],
    'vormleer-hoeken-herkennen': ['vormleer-hoeken', 'Hoeken · herkennen', 'Welke soort hoek is dit?', 0],
    'vormleer-vierhoeken': ['vormleer-figuren', 'Vlakke figuren · vierhoeken', 'Welke vierhoek is dit?', 1],
    'temperatuur-aflezen': ['temperatuur', 'Temperatuur aflezen', 'Lees de temperatuur af.', 0],
    'temperatuur-verschil': ['temperatuur', 'Temperatuurverschil', 'Bereken het verschil in temperatuur.', 0, { variant: 'verschil', mode1: 'gekleurd', mode2: 'getal' }],
    'massa-weegschaal-aflezen': ['weegschaal', 'Weegschaal aflezen', 'Lees het gewicht af.', 0],
    'oppervlakte-rooster': ['oppervlakte', 'Oppervlakte · rooster tellen', 'Tel de vierkantjes. Wat is de oppervlakte?', 0],
    'oppervlakte-berekenen': ['oppervlakte', 'Oppervlakte · berekenen', 'Bereken de oppervlakte.', 0, { subType: 'berekenen', shapes: ['rechthoek', 'vierkant'] }],
    'maateenheid-kiezen': ['maateenheid', 'Passende maateenheid kiezen', 'Omcirkel de passende maateenheid.', 1],
    'herleidingen-lengte': ['herleidingen', 'Herleiden · lengte', 'Zet om.', 0],
    'herleidingen-inhoud': ['herleidingen', 'Herleiden · inhoud', 'Zet om.', 0, { measure: 'inhoud', units: ['l', 'dl', 'cl', 'ml'] }],
    'herleidingen-massa': ['herleidingen', 'Herleiden · massa', 'Zet om.', 0, { measure: 'massa', units: ['kg', 'dag', 'g', 'dg'] }],
    'herleidingen-oppervlakte': ['herleidingen', 'Herleiden · oppervlakte', 'Zet om.', 0, { measure: 'oppervlakte', units: ['m²', 'dm²', 'cm²', 'a', 'ca', 'ha'] }],
    'geld-herkennen': ['geld-herkennen', 'Geld herkennen', 'Hoeveel geld is dit?', 0],
    'geld-teruggeven': ['geld-teruggeven', 'Geld teruggeven', 'Hoeveel krijg je terug?', 0],
    'geld-rekenen-korting': ['geld-rekenen', 'Korting berekenen', 'Bereken de korting en de nieuwe prijs.', 0],
    'geld-rekenen-intrest': ['geld-rekenen', 'Intrest berekenen', 'Bereken de intrest.', 0, { subType: 'intrest', percents: [1, 2, 5], maxEuro: 10000 }],
    'lengte-meten': ['lengte-meten', 'Lengte meten', 'Meet.', 1],
    omtrek: ['omtrek', 'Omtrek', 'Bereken de omtrek.', 0],
    'splitsen-basis': ['splitsen', 'Splitsen · rooster', 'Splits het getal.', 0],
    'splitsen-boom': ['splitsen', 'Splitsen · splitsboom', 'Vul de splitsboom aan.', 0, { maxGetal: 100, layout: 'splitsboom', blankPositions: ['right'] }],
    'splitsen-harten': ['splitsen', 'Splitsen · verliefde harten', 'Vul de verliefde harten aan.', 0, { layout: 'verliefde-harten' }],
    'splitsen-positietabel': ['splitsen', 'Splitsen · positietabel', 'Vul de positietabel in.', 0, { maxGetal: 1000, layout: 'positie-tabel' }],
    'getalbegrip-ordenen-nat': ['ordenen', 'Ordenen · natuurlijk', 'Zet in volgorde van klein naar groot.', 1],
    'getalbegrip-ordenen-dec': ['ordenen', 'Ordenen · decimaal', 'Zet in volgorde van klein naar groot.', 1, { numberType: 'decimal' }],
    'getalbegrip-ordenen-rat': ['ordenen', 'Ordenen · breuken', 'Zet in volgorde van klein naar groot.', 1, { numberType: 'rational', maxGetal: 100 }],
    'getalbegrip-ordenen-geh': ['ordenen', 'Ordenen · geheel', 'Zet in volgorde van klein naar groot.', 1, { numberType: 'geheel' }],
    'getalbegrip-getallenassen-nat': ['getallenas', 'Getallenassen · natuurlijk', 'Vul de getallenas aan.', 0],
    'getalbegrip-getallenassen-dec': ['getallenas', 'Getallenassen · decimaal', 'Vul de getallenas aan.', 0, { numberType: 'decimal', maxGetal: 20, step: 0.5 }],
    'getalbegrip-getallenassen-rat': ['getallenas', 'Getallenassen · breuken', 'Vul de getallenas aan.', 0, { numberType: 'rational', maxGetal: 100, fractionStep: 4 }],
    'getalbegrip-getallenassen-geh': ['getallenas', 'Getallenassen · geheel', 'Vul de getallenas aan.', 0, { numberType: 'geheel', maxGetal: 20 }],
    'getalbegrip-getallenrijen-nat': ['getallenrijen', 'Getallenrijen · natuurlijk', 'Vul de getallenrij aan.', 0],
    'getalbegrip-getallenrijen-dec': ['getallenrijen', 'Getallenrijen · decimaal', 'Vul de getallenrij aan.', 0, { numberType: 'decimal', maxGetal: 10, step: 0.1 }],
    'getalbegrip-getallenrijen-rat': ['getallenrijen', 'Getallenrijen · breuken', 'Vul de getallenrij aan.', 0, { numberType: 'rational', maxGetal: 100 }],
    'getalbegrip-getallenrijen-geh': ['getallenrijen', 'Getallenrijen · geheel', 'Vul de getallenrij aan.', 0, { numberType: 'geheel', maxGetal: 20 }],
    'breuken-rangschikken': ['breuken-rangschikken', 'Breuken rangschikken', 'Zet de breuken in volgorde van klein naar groot.', 1],
    'patronen-nat': ['getalpatronen', 'Patronen · natuurlijk', 'Zet de rij verder.', 0],
    'patronen-dec': ['getalpatronen', 'Patronen · decimaal', 'Zet de rij verder.', 0, { numberType: 'decimal', maxGetal: 100 }],
    'patronen-geh': ['getalpatronen', 'Patronen · geheel', 'Zet de rij verder.', 0, { numberType: 'geheel', maxGetal: 100 }],
    'patronen-kettingsommen': ['kettingsommen', 'Kettingsommen', 'Reken de kettingsom uit.', 0],
    'deelbaarheid-veelvouden': ['deelbaarheid', 'Veelvouden aanvullen', 'Vul de veelvouden aan.', 0],
    'breuken-herkennen': ['breuken', 'Breuken herkennen', 'Welk deel is gekleurd? Schrijf de breuk.', 0],
    'breuken-hoeveelheid': ['breuken', 'Breuk van een hoeveelheid', 'Bereken de breuk van de hoeveelheid.', 0, { subType: 'hoeveelheid', maxDenominator: 5, answerFormat: 'met-hulp' }],
    'breuken-gemengd': ['breuken-bewerken', 'Gemengd getal ↔ breuk', 'Schrijf als gemengd getal.', 1],
    'breuken-gelijknamig': ['breuken-bewerken', 'Gelijknamig maken', 'Maak gelijknamig.', 0, { subType: 'gelijknamig' }],
    'breuken-vereenvoudigen': ['breuken-bewerken', 'Vereenvoudigen', 'Vereenvoudig.', 0, { subType: 'vereenvoudigen' }],
    'verbanden-tabel': ['verbanden', 'Verbanden · tabel invullen', 'Vul de tabel aan: breuk, kommagetal en procent.', 0],
    'verbanden-paren': ['verbanden', 'Verbanden · omzettingen', 'Zet om.', 0, { subType: 'paren' }],
    'procenten-verbanden': ['verbanden', 'Breuk · decimaal · procent', 'Vul de tabel aan: breuk, kommagetal en procent.', 0],
    'klok-analoog-lezen': ['klok-kloklezen', 'Analoge klok · lezen', 'Hoe laat is het?', 0],
    'klok-analoog-omzetten': ['klok-kloklezen', 'Analoge klok · omzetten', 'Schrijf de tijd digitaal.', 0, { exerciseMode: 'omzetten' }],
    'klok-digitaal-tekenen': ['klok-kloklezen', 'Digitale klok · tekenen', 'Vul de digitale klok in.', 0, { clockType: 'digitaal', exerciseMode: 'tekenen' }],
    'tijdsduur-berekenen': ['tijdsduur', 'Tijdsduur berekenen', 'Vul in: begin, einde of duur.', 0],
    'even-oneven-rooster': ['even-oneven', 'Rooster kleuren', 'Kleur de even getallen.', 1, { subType: 'rooster', maxGetal: 1000 }],
    'deelbaarheid-tabel': ['deelbaarheid', 'Deelbaarheidstabel', 'Kruis aan: door welke getallen is het getal deelbaar?', 0, { layout: 'tabel' }],
    'deelbaarheid-rooster': ['deelbaarheid-kleuren', 'Deelbaarheid · rooster', 'Kleur de veelvouden van 2, 5 en 10.', 1],
    'deelbaarheid-omcirkelen': ['deelbaarheid-kleuren', 'Deelbaarheid · omcirkelen', 'Omcirkel de veelvouden van 2, 5 en 10.', 1, { viewMode: 'markeren' }],
    'deelbaarheid-kleurraster': ['deelbaarheid-kleuren', 'Deelbaarheid · kleurraster', 'Kleur de veelvouden van 2, 5 en 10.', 1, { rasterVorm: 'rechthoek' }],
    'breuken-kleuren': ['breuken', 'Breuken kleuren', 'Kleur de breuk.', 0, { subType: 'kleuren' }],
    'afronden-nat-rooster': ['afronden', 'Afronden · natuurlijk · rooster', 'Rond af op T en H.', 1, { subType: 'rooster' }],
    'afronden-dec-rooster': ['afronden', 'Afronden · decimaal · rooster', 'Rond af op E en t.', 1, { subType: 'rooster', numberType: 'decimal', maxGetal: 100, roundTargets: ['E', 't'] }],
    'plaatswaarde-tabel': ['plaatswaarde', 'Plaatswaarde benoemen · tabel invullen', 'Vul de plaatswaardetabel in.', 0, { subType: 'tabel' }],
    'geld-tekenen': ['geld-tekenen', 'Bedrag tekenen', 'Teken het bedrag.', 0],
    'geld-wissel': ['geld-wissel', 'Wissel', 'Wissel het bedrag.', 0],
    'mab-tekenen': ['mab-tekenen', 'MAB · getallen tekenen', 'Teken het getal met MAB-materiaal.', 0],
    'klok-analoog-tekenen': ['klok-kloklezen', 'Analoge klok · tekenen', 'Teken de wijzers.', 0, { exerciseMode: 'tekenen' }],
    'vormleer-hoeken-tekenen': ['vormleer-hoeken', 'Hoeken · tekenen', 'Teken de hoek.', 0, { mode: 'tekenen' }],
    'temperatuur-kleuren': ['temperatuur', 'Meter kleuren', 'Kleur de thermometer.', 0, { variant: 'kleuren' }],
    'massa-weegschaal-tekenen': ['weegschaal', 'Weegschaal kleuren', 'Kleur de weegschaal tot het gegeven gewicht.', 0, { mode: 'kleuren' }],
};

export interface KioskDefault {
    typeId: string;
    label: string;
    instruction: string;
    // The leaf's instruction depends on its settings: `instruction` only holds for the seed.
    dynInstruction: boolean;
    constraints: Constraints;
}

export const KIOSK_DEFAULTS_V1_LEAVES: readonly string[] = Object.keys(LEAVES);

/** The frozen defaults of a leaf (a fresh copy), or undefined when the snapshot predates it. */
export function kioskDefaultV1(leafId: string): KioskDefault | undefined {
    const row = Object.prototype.hasOwnProperty.call(LEAVES, leafId) ? LEAVES[leafId] : undefined;
    if (!row) return undefined;
    const [typeId, label, instruction, dyn, diff, removed] = row;
    const constraints = JSON.parse(JSON.stringify({ ...TYPES[typeId], ...diff })) as Constraints;
    for (const k of removed ?? []) delete constraints[k];
    return { typeId, label, instruction, dynInstruction: dyn === 1, constraints };
}
