import { describe, test, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { flattenLeaves } from '../config/appstructure';

// The public exercise catalogue (oefeningen.html, generated by scripts/catalogue.mjs) is a
// snapshot of the sidebar leaves. A leaf added, removed or renamed without `npm run
// catalogue` would ship a stale page — so the gate compares the two sets, not the script.
const ROOT = join(__dirname, '..', '..');
const PAGE = join(ROOT, 'oefeningen.html');

describe('oefeningen.html matches APP_STRUCTURE', () => {
    const html = existsSync(PAGE) ? readFileSync(PAGE, 'utf8') : '';
    const inPage = new Set([...html.matchAll(/data-leaf="([^"]+)"/g)].map(m => m[1]));
    const leaves = flattenLeaves();

    test('the page exists and carries data-leaf cards', () => {
        expect(html.length).toBeGreaterThan(0);
        expect(inPage.size).toBeGreaterThan(0);
    });

    test('every sidebar leaf has a card (run `npm run catalogue` when this fails)', () => {
        const missing = leaves.map(l => l.id).filter(id => !inPage.has(id));
        expect(missing).toEqual([]);
    });

    test('no card is left for a leaf that no longer exists', () => {
        const ids = new Set(leaves.map(l => l.id));
        const stale = [...inPage].filter(id => !ids.has(id));
        expect(stale).toEqual([]);
    });

    test('every card has its screenshot', () => {
        const noPng = leaves.map(l => l.id).filter(id => !existsSync(join(ROOT, 'public', 'oefeningen', `${id}.png`)));
        expect(noPng).toEqual([]);
    });
});
